6. Write a program in Java to demonstrate exception handling

package Phase_One;

import java.util.*;
public class Exception_1
{
public static void main(String[] args) 
{
  Scanner sc = new Scanner(System.in);
  System.out.println("enter a first number ");
  int num1 = sc.nextInt();
  System.out.println("enter a second number ");
  int num2 = sc.nextInt();
  int result;
  
  try {
	  result = num1/num2;
	  System.out.println("Result : " + result);
  }
  catch(ArithmeticException ae)
  {
	  System.out.println("Exception :Division by zero");
  }
 
  }Output:1
	enter a first number 
	5
	enter a second number 
	2
	Result : 2

	Output : 2
	enter a first number 
	5
	enter a second number 
	0
	Exception :Division by zero
